### PR TITLE
Add startup scripts

### LINKED ISSUE #52: Add startup script
I guess when we have script

```js
class Startup {
    async invoke() {
    }
}
```

We should automatically load it on Startup

### PR DESCRIPTION
**Pull request by mnaoumov**
Fixes #52

### CODE REVIEW

**Comment by saml-dev** [comment]
it looks like this needs to be updated to match your mega PR (having the setting be an array). Smaller PRs are preferred for easier review

**Comment by mnaoumov** [comment]
@saml-dev, yes, I tried to make them one by one, but since it's all in one file, I need to resolve merge conflicts over and over. That's fine as soon as you are willing to review my changes

**Comment by saml-dev** [comment]
Yeah I get it, that's a bit annoying to keep resolving. I just merged two of your PRs so maybe it'll be a bit easier now

**Comment by mnaoumov** [comment]
Depends on #57

**Comment by saml-dev** [comment]
I'll review this one once conflicts are resolved. Doesn't look too bad on this one

**Comment by mnaoumov** [comment]
@saml-dev rebased to fix merge conflicts

**Review by saml-dev — APPROVED** [review]

**Pull request merged**
